# Site
title: "Введение в программирование на Go"
url: "http://golang-book.ru"
locale: "ru"
baseurl: ""

exclude:
  - vendor

# Collections
collections:
  book:
    output: true
    permalink: '/:name.html'

# Build
permalink: /:title.html
markdown: redcarpet
highlighter: null

# Assets
assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: false

# Assets
assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: false

# Markdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - tables
    - footnotes
